// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth_query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const changePassword = `-- name: ChangePassword :exec
update sys_user set password = $1, salt = $2 where uuid = $3
`

type ChangePasswordParams struct {
	Password pgtype.Text
	Salt     pgtype.Text
	Uuid     pgtype.UUID
}

func (q *Queries) ChangePassword(ctx context.Context, arg ChangePasswordParams) error {
	_, err := q.db.Exec(ctx, changePassword, arg.Password, arg.Salt, arg.Uuid)
	return err
}

const checkHasPermission = `-- name: CheckHasPermission :one
select u.uuid
from sys_user u
         join user_role ur on u.uuid = ur.user_uuid
         join role_group rg on rg.role_uuid = ur.role_uuid
         join group_resource gr on gr.group_uuid = rg.group_uuid
         join resource r on gr.resource_uuid = r.uuid
where u.uuid = $1
  and r.value = $2
`

type CheckHasPermissionParams struct {
	Uuid  pgtype.UUID
	Value pgtype.Text
}

func (q *Queries) CheckHasPermission(ctx context.Context, arg CheckHasPermissionParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, checkHasPermission, arg.Uuid, arg.Value)
	var uuid pgtype.UUID
	err := row.Scan(&uuid)
	return uuid, err
}
