// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: batch.go

package db

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const addResourcesToGroup = `-- name: AddResourcesToGroup :batchexec
insert into group_resource (group_uuid, resource_uuid)
values ($1, $2)
`

type AddResourcesToGroupBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type AddResourcesToGroupParams struct {
	GroupUuid    pgtype.UUID
	ResourceUuid pgtype.UUID
}

func (q *Queries) AddResourcesToGroup(ctx context.Context, arg []AddResourcesToGroupParams) *AddResourcesToGroupBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.GroupUuid,
			a.ResourceUuid,
		}
		batch.Queue(addResourcesToGroup, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &AddResourcesToGroupBatchResults{br, len(arg), false}
}

func (b *AddResourcesToGroupBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *AddResourcesToGroupBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const addRolesToGroup = `-- name: AddRolesToGroup :batchexec
insert into role_group (role_uuid, group_uuid)
values ($1, $2)
`

type AddRolesToGroupBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type AddRolesToGroupParams struct {
	RoleUuid  pgtype.UUID
	GroupUuid pgtype.UUID
}

func (q *Queries) AddRolesToGroup(ctx context.Context, arg []AddRolesToGroupParams) *AddRolesToGroupBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.RoleUuid,
			a.GroupUuid,
		}
		batch.Queue(addRolesToGroup, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &AddRolesToGroupBatchResults{br, len(arg), false}
}

func (b *AddRolesToGroupBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *AddRolesToGroupBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const addUsersToRole = `-- name: AddUsersToRole :batchexec
insert into user_role (role_uuid, user_uuid)
values ($1, $2)
`

type AddUsersToRoleBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type AddUsersToRoleParams struct {
	RoleUuid pgtype.UUID
	UserUuid pgtype.UUID
}

func (q *Queries) AddUsersToRole(ctx context.Context, arg []AddUsersToRoleParams) *AddUsersToRoleBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.RoleUuid,
			a.UserUuid,
		}
		batch.Queue(addUsersToRole, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &AddUsersToRoleBatchResults{br, len(arg), false}
}

func (b *AddUsersToRoleBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *AddUsersToRoleBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const batchInsertResources = `-- name: BatchInsertResources :batchexec
insert into resource (value) values ($1)
`

type BatchInsertResourcesBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

func (q *Queries) BatchInsertResources(ctx context.Context, value []pgtype.Text) *BatchInsertResourcesBatchResults {
	batch := &pgx.Batch{}
	for _, a := range value {
		vals := []interface{}{
			a,
		}
		batch.Queue(batchInsertResources, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &BatchInsertResourcesBatchResults{br, len(value), false}
}

func (b *BatchInsertResourcesBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *BatchInsertResourcesBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const createAchievementCategoryValue = `-- name: CreateAchievementCategoryValue :batchexec
insert into achievement_category_value (achievement_uuid, category_value_uuid)
VALUES ($1, (select cv.uuid from category_value cv where cv.category_uuid = $2 and cv.name = $3))
`

type CreateAchievementCategoryValueBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type CreateAchievementCategoryValueParams struct {
	AchievementUuid pgtype.UUID
	CategoryUuid    pgtype.UUID
	Name            string
}

func (q *Queries) CreateAchievementCategoryValue(ctx context.Context, arg []CreateAchievementCategoryValueParams) *CreateAchievementCategoryValueBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.AchievementUuid,
			a.CategoryUuid,
			a.Name,
		}
		batch.Queue(createAchievementCategoryValue, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &CreateAchievementCategoryValueBatchResults{br, len(arg), false}
}

func (b *CreateAchievementCategoryValueBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *CreateAchievementCategoryValueBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const createBatchAchievementCategory = `-- name: CreateBatchAchievementCategory :batchexec
insert into achievement_category (category_uuid, achievement_uuid)
values ($1, $2)
`

type CreateBatchAchievementCategoryBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type CreateBatchAchievementCategoryParams struct {
	CategoryUuid    pgtype.UUID
	AchievementUuid pgtype.UUID
}

func (q *Queries) CreateBatchAchievementCategory(ctx context.Context, arg []CreateBatchAchievementCategoryParams) *CreateBatchAchievementCategoryBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.CategoryUuid,
			a.AchievementUuid,
		}
		batch.Queue(createBatchAchievementCategory, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &CreateBatchAchievementCategoryBatchResults{br, len(arg), false}
}

func (b *CreateBatchAchievementCategoryBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *CreateBatchAchievementCategoryBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const createCategoryValues = `-- name: CreateCategoryValues :batchexec
insert into category_value (name, category_uuid, point)
VALUES ($1, $2, $3)
on conflict (name, category_uuid) do update set point = $3, status_uuid = (select s.uuid from status s where type = 'category_status' and internal_value = 'active')
`

type CreateCategoryValuesBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type CreateCategoryValuesParams struct {
	Name         string
	CategoryUuid pgtype.UUID
	Point        pgtype.Numeric
}

func (q *Queries) CreateCategoryValues(ctx context.Context, arg []CreateCategoryValuesParams) *CreateCategoryValuesBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.Name,
			a.CategoryUuid,
			a.Point,
		}
		batch.Queue(createCategoryValues, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &CreateCategoryValuesBatchResults{br, len(arg), false}
}

func (b *CreateCategoryValuesBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *CreateCategoryValuesBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const makeCategoryValueUnactive = `-- name: MakeCategoryValueUnactive :batchexec
update category_value cv
set status_uuid = (select s.uuid from status s where s.type = 'category_value_status' and s.internal_value = 'unactive')
where cv.name = $1
`

type MakeCategoryValueUnactiveBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

func (q *Queries) MakeCategoryValueUnactive(ctx context.Context, name []string) *MakeCategoryValueUnactiveBatchResults {
	batch := &pgx.Batch{}
	for _, a := range name {
		vals := []interface{}{
			a,
		}
		batch.Queue(makeCategoryValueUnactive, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &MakeCategoryValueUnactiveBatchResults{br, len(name), false}
}

func (b *MakeCategoryValueUnactiveBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *MakeCategoryValueUnactiveBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const recreateCategoryValues = `-- name: RecreateCategoryValues :batchexec
update category_value cv
set status_uuid = (select s.uuid from status s where s.type = 'category_value_status' and s.internal_value = 'active'),
    point = $1
where cv.name = $2
`

type RecreateCategoryValuesBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type RecreateCategoryValuesParams struct {
	Point pgtype.Numeric
	Name  string
}

func (q *Queries) RecreateCategoryValues(ctx context.Context, arg []RecreateCategoryValuesParams) *RecreateCategoryValuesBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.Point,
			a.Name,
		}
		batch.Queue(recreateCategoryValues, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &RecreateCategoryValuesBatchResults{br, len(arg), false}
}

func (b *RecreateCategoryValuesBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *RecreateCategoryValuesBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const removeBatchAchievementCategory = `-- name: RemoveBatchAchievementCategory :batchexec
delete
from achievement_category
where category_uuid = $1
  and achievement_uuid = $2
`

type RemoveBatchAchievementCategoryBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type RemoveBatchAchievementCategoryParams struct {
	CategoryUuid    pgtype.UUID
	AchievementUuid pgtype.UUID
}

func (q *Queries) RemoveBatchAchievementCategory(ctx context.Context, arg []RemoveBatchAchievementCategoryParams) *RemoveBatchAchievementCategoryBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.CategoryUuid,
			a.AchievementUuid,
		}
		batch.Queue(removeBatchAchievementCategory, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &RemoveBatchAchievementCategoryBatchResults{br, len(arg), false}
}

func (b *RemoveBatchAchievementCategoryBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *RemoveBatchAchievementCategoryBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
