// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: batch.go

package db

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const addResourcesToGroup = `-- name: AddResourcesToGroup :batchexec
insert into group_resource (group_uuid, resource_uuid)
values ($1, $2)
`

type AddResourcesToGroupBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type AddResourcesToGroupParams struct {
	GroupUuid    pgtype.UUID
	ResourceUuid pgtype.UUID
}

func (q *Queries) AddResourcesToGroup(ctx context.Context, arg []AddResourcesToGroupParams) *AddResourcesToGroupBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.GroupUuid,
			a.ResourceUuid,
		}
		batch.Queue(addResourcesToGroup, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &AddResourcesToGroupBatchResults{br, len(arg), false}
}

func (b *AddResourcesToGroupBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *AddResourcesToGroupBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const addRolesToGroup = `-- name: AddRolesToGroup :batchexec
insert into role_group (role_uuid, group_uuid)
values ($1, $2)
`

type AddRolesToGroupBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type AddRolesToGroupParams struct {
	RoleUuid  pgtype.UUID
	GroupUuid pgtype.UUID
}

func (q *Queries) AddRolesToGroup(ctx context.Context, arg []AddRolesToGroupParams) *AddRolesToGroupBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.RoleUuid,
			a.GroupUuid,
		}
		batch.Queue(addRolesToGroup, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &AddRolesToGroupBatchResults{br, len(arg), false}
}

func (b *AddRolesToGroupBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *AddRolesToGroupBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const addUsersToRole = `-- name: AddUsersToRole :batchexec
insert into user_role (role_uuid, user_uuid)
values ($1, $2)
`

type AddUsersToRoleBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type AddUsersToRoleParams struct {
	RoleUuid pgtype.UUID
	UserUuid pgtype.UUID
}

func (q *Queries) AddUsersToRole(ctx context.Context, arg []AddUsersToRoleParams) *AddUsersToRoleBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.RoleUuid,
			a.UserUuid,
		}
		batch.Queue(addUsersToRole, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &AddUsersToRoleBatchResults{br, len(arg), false}
}

func (b *AddUsersToRoleBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *AddUsersToRoleBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const batchInsertResources = `-- name: BatchInsertResources :batchexec
insert into resource (value) values ($1)
`

type BatchInsertResourcesBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

func (q *Queries) BatchInsertResources(ctx context.Context, value []pgtype.Text) *BatchInsertResourcesBatchResults {
	batch := &pgx.Batch{}
	for _, a := range value {
		vals := []interface{}{
			a,
		}
		batch.Queue(batchInsertResources, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &BatchInsertResourcesBatchResults{br, len(value), false}
}

func (b *BatchInsertResourcesBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *BatchInsertResourcesBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
