// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: category_query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
insert into category (name, point_amount, parent_category)
values ($1, $2, $3)
returning uuid
`

type CreateCategoryParams struct {
	Name           string
	PointAmount    pgtype.Numeric
	ParentCategory pgtype.UUID
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.Name, arg.PointAmount, arg.ParentCategory)
	var uuid pgtype.UUID
	err := row.Scan(&uuid)
	return uuid, err
}

const deleteCategory = `-- name: DeleteCategory :exec
update category c
set status_uuid = (select s.uuid from status s where s.internal_value = 'unactive' and s.type = 'category_status')
where c.uuid = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, uuid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCategory, uuid)
	return err
}

const deleteCategoryValues = `-- name: DeleteCategoryValues :exec
delete from category_value where category_uuid = $1
`

func (q *Queries) DeleteCategoryValues(ctx context.Context, categoryUuid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCategoryValues, categoryUuid)
	return err
}

const getCategoryByAchievement = `-- name: GetCategoryByAchievement :many
select c.uuid, c.name, c.point_amount, c.parent_category, c.comment, c.status_uuid, s.display_value as status_value
from category c
         join achievement_category ac on c.uuid = ac.category_uuid
         join status s on s.uuid = c.status_uuid
where achievement_uuid = $1
`

type GetCategoryByAchievementRow struct {
	Uuid           pgtype.UUID
	Name           string
	PointAmount    pgtype.Numeric
	ParentCategory pgtype.UUID
	Comment        pgtype.Text
	StatusUuid     pgtype.UUID
	StatusValue    pgtype.Text
}

func (q *Queries) GetCategoryByAchievement(ctx context.Context, achievementUuid pgtype.UUID) ([]GetCategoryByAchievementRow, error) {
	rows, err := q.db.Query(ctx, getCategoryByAchievement, achievementUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCategoryByAchievementRow
	for rows.Next() {
		var i GetCategoryByAchievementRow
		if err := rows.Scan(
			&i.Uuid,
			&i.Name,
			&i.PointAmount,
			&i.ParentCategory,
			&i.Comment,
			&i.StatusUuid,
			&i.StatusValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoryByNameAndParentNull = `-- name: GetCategoryByNameAndParentNull :one
select uuid, name, point_amount, parent_category, comment, status_uuid
from category
where name = $1
  and parent_category is null
`

func (q *Queries) GetCategoryByNameAndParentNull(ctx context.Context, name string) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByNameAndParentNull, name)
	var i Category
	err := row.Scan(
		&i.Uuid,
		&i.Name,
		&i.PointAmount,
		&i.ParentCategory,
		&i.Comment,
		&i.StatusUuid,
	)
	return i, err
}

const getCategoryByNameAndParentUUID = `-- name: GetCategoryByNameAndParentUUID :one
select uuid, name, point_amount, parent_category, comment, status_uuid
from category
where name = $1
  and parent_category = $2
`

type GetCategoryByNameAndParentUUIDParams struct {
	Name           string
	ParentCategory pgtype.UUID
}

func (q *Queries) GetCategoryByNameAndParentUUID(ctx context.Context, arg GetCategoryByNameAndParentUUIDParams) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByNameAndParentUUID, arg.Name, arg.ParentCategory)
	var i Category
	err := row.Scan(
		&i.Uuid,
		&i.Name,
		&i.PointAmount,
		&i.ParentCategory,
		&i.Comment,
		&i.StatusUuid,
	)
	return i, err
}

const getCategoryByUUID = `-- name: GetCategoryByUUID :one
select c.uuid, c.name, c.point_amount, c.parent_category, c.comment, s.display_value
from category c
         join status s on c.status_uuid = s.uuid and type = 'category_status'
where c.uuid = $1
`

type GetCategoryByUUIDRow struct {
	Uuid           pgtype.UUID
	Name           string
	PointAmount    pgtype.Numeric
	ParentCategory pgtype.UUID
	Comment        pgtype.Text
	DisplayValue   pgtype.Text
}

func (q *Queries) GetCategoryByUUID(ctx context.Context, uuid pgtype.UUID) (GetCategoryByUUIDRow, error) {
	row := q.db.QueryRow(ctx, getCategoryByUUID, uuid)
	var i GetCategoryByUUIDRow
	err := row.Scan(
		&i.Uuid,
		&i.Name,
		&i.PointAmount,
		&i.ParentCategory,
		&i.Comment,
		&i.DisplayValue,
	)
	return i, err
}

const getChildCategories = `-- name: GetChildCategories :many
select c.uuid, c.name as category_name,cv.name as value_name, cv.point
from category c
         join category_value cv on c.uuid = cv.category_uuid
where c.parent_category = $1
`

type GetChildCategoriesRow struct {
	Uuid         pgtype.UUID
	CategoryName string
	ValueName    string
	Point        pgtype.Numeric
}

func (q *Queries) GetChildCategories(ctx context.Context, parentCategory pgtype.UUID) ([]GetChildCategoriesRow, error) {
	rows, err := q.db.Query(ctx, getChildCategories, parentCategory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChildCategoriesRow
	for rows.Next() {
		var i GetChildCategoriesRow
		if err := rows.Scan(
			&i.Uuid,
			&i.CategoryName,
			&i.ValueName,
			&i.Point,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParentCategories = `-- name: ListParentCategories :many
select c.uuid, c.name, c.point_amount, c.comment, s.display_value
from category c
         join status s on c.status_uuid = s.uuid and type = 'category_status'
where parent_category is null
`

type ListParentCategoriesRow struct {
	Uuid         pgtype.UUID
	Name         string
	PointAmount  pgtype.Numeric
	Comment      pgtype.Text
	DisplayValue pgtype.Text
}

func (q *Queries) ListParentCategories(ctx context.Context) ([]ListParentCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listParentCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListParentCategoriesRow
	for rows.Next() {
		var i ListParentCategoriesRow
		if err := rows.Scan(
			&i.Uuid,
			&i.Name,
			&i.PointAmount,
			&i.Comment,
			&i.DisplayValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParentCategoriesWithPagination = `-- name: ListParentCategoriesWithPagination :many
select c.uuid, c.name, c.point_amount, s.display_value, count(c.uuid) over () as total_amount
from category c
         join status s on c.status_uuid = s.uuid and type = 'category_status'
where parent_category is null
limit $1 offset $2
`

type ListParentCategoriesWithPaginationParams struct {
	Limit  int32
	Offset int32
}

type ListParentCategoriesWithPaginationRow struct {
	Uuid         pgtype.UUID
	Name         string
	PointAmount  pgtype.Numeric
	DisplayValue pgtype.Text
	TotalAmount  int64
}

func (q *Queries) ListParentCategoriesWithPagination(ctx context.Context, arg ListParentCategoriesWithPaginationParams) ([]ListParentCategoriesWithPaginationRow, error) {
	rows, err := q.db.Query(ctx, listParentCategoriesWithPagination, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListParentCategoriesWithPaginationRow
	for rows.Next() {
		var i ListParentCategoriesWithPaginationRow
		if err := rows.Scan(
			&i.Uuid,
			&i.Name,
			&i.PointAmount,
			&i.DisplayValue,
			&i.TotalAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :exec
update category
set name         = $1,
    point_amount = $2,
    status_uuid  = (select s.uuid from status s where s.display_value = $3 and s.type = 'category_status')
where category.uuid = $4
`

type UpdateCategoryParams struct {
	Name         string
	PointAmount  pgtype.Numeric
	DisplayValue pgtype.Text
	Uuid         pgtype.UUID
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) error {
	_, err := q.db.Exec(ctx, updateCategory,
		arg.Name,
		arg.PointAmount,
		arg.DisplayValue,
		arg.Uuid,
	)
	return err
}
