// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: category_query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
insert into category (name, point_amount, parent_category, comment)
values ($1, $2, $3, $4)
    returning uuid
`

type CreateCategoryParams struct {
	Name           string
	PointAmount    pgtype.Numeric
	ParentCategory pgtype.UUID
	Comment        pgtype.Text
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.Name,
		arg.PointAmount,
		arg.ParentCategory,
		arg.Comment,
	)
	var uuid pgtype.UUID
	err := row.Scan(&uuid)
	return uuid, err
}

const getCategoryByName = `-- name: GetCategoryByName :one
select uuid, name, point_amount, parent_category, comment, status_uuid from category where name = $1
`

func (q *Queries) GetCategoryByName(ctx context.Context, name string) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByName, name)
	var i Category
	err := row.Scan(
		&i.Uuid,
		&i.Name,
		&i.PointAmount,
		&i.ParentCategory,
		&i.Comment,
		&i.StatusUuid,
	)
	return i, err
}

const getCategoryByUUID = `-- name: GetCategoryByUUID :one
select uuid, name, point_amount, parent_category, comment, status_uuid from category where uuid = $1
`

func (q *Queries) GetCategoryByUUID(ctx context.Context, uuid pgtype.UUID) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByUUID, uuid)
	var i Category
	err := row.Scan(
		&i.Uuid,
		&i.Name,
		&i.PointAmount,
		&i.ParentCategory,
		&i.Comment,
		&i.StatusUuid,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
select uuid, name, point_amount, parent_category, comment, status_uuid from category limit $1 offset $2
`

type ListCategoriesParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListCategories(ctx context.Context, arg ListCategoriesParams) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.Uuid,
			&i.Name,
			&i.PointAmount,
			&i.ParentCategory,
			&i.Comment,
			&i.StatusUuid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
