// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: constant.sql

package db

import (
	"context"
)

const changeGradesConstant = `-- name: ChangeGradesConstant :exec
update constants
set value = $1
where name = 'available_student_grades'
`

func (q *Queries) ChangeGradesConstant(ctx context.Context, value string) error {
	_, err := q.db.Exec(ctx, changeGradesConstant, value)
	return err
}

const getGradesConstant = `-- name: GetGradesConstant :one
select value
from constants
where name = 'available_student_grades'
`

func (q *Queries) GetGradesConstant(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, getGradesConstant)
	var value string
	err := row.Scan(&value)
	return value, err
}
