// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type SystemUserType string

const (
	SystemUserTypeStudent SystemUserType = "student"
	SystemUserTypeAdmin   SystemUserType = "admin"
)

func (e *SystemUserType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SystemUserType(s)
	case string:
		*e = SystemUserType(s)
	default:
		return fmt.Errorf("unsupported scan type for SystemUserType: %T", src)
	}
	return nil
}

type NullSystemUserType struct {
	SystemUserType SystemUserType
	Valid          bool // Valid is true if SystemUserType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSystemUserType) Scan(value interface{}) error {
	if value == nil {
		ns.SystemUserType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SystemUserType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSystemUserType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SystemUserType), nil
}

type AcheivementCategory struct {
	CategoryUuid    pgtype.UUID
	AchievementUuid pgtype.UUID
}

type Achievement struct {
	Uuid           pgtype.UUID
	Comment        pgtype.Text
	AttachmentLink string
	UserUuid       pgtype.UUID
	StatusUuid     pgtype.UUID
}

type Category struct {
	Uuid           pgtype.UUID
	Name           string
	PointAmount    pgtype.Numeric
	ParentCategory pgtype.UUID
	Comment        pgtype.Text
	StatusUuid     string
}

type Status struct {
	Uuid          pgtype.UUID
	InternalValue pgtype.Text
	DisplayValue  pgtype.Text
	Type          pgtype.Text
}

type SysUser struct {
	Uuid            pgtype.UUID
	Name            string
	SecondName      string
	Patronymic      pgtype.Text
	GradebookNumber string
	BirthDate       pgtype.Date
	Email           pgtype.Text
	PhoneNumber     pgtype.Text
	StatusUuid      pgtype.UUID
	Type            NullSystemUserType
}
