// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AcheivementCategory struct {
	CategoryUuid    pgtype.UUID
	AchievementUuid pgtype.UUID
}

type Achievement struct {
	Uuid           pgtype.UUID
	Comment        pgtype.Text
	AttachmentLink string
	UserUuid       pgtype.UUID
	StatusUuid     pgtype.UUID
}

type AuthGroup struct {
	Uuid pgtype.UUID
	Name string
}

type AuthRole struct {
	Uuid pgtype.UUID
	Name string
}

type Category struct {
	Uuid           pgtype.UUID
	Name           string
	PointAmount    pgtype.Numeric
	ParentCategory pgtype.UUID
	Comment        pgtype.Text
	StatusUuid     pgtype.UUID
}

type GroupResource struct {
	GroupUuid    pgtype.UUID
	ResourceUuid pgtype.UUID
}

type Resource struct {
	Uuid  pgtype.UUID
	Value pgtype.Text
}

type RoleGroup struct {
	RoleUuid  pgtype.UUID
	GroupUuid pgtype.UUID
}

type Status struct {
	Uuid          pgtype.UUID
	InternalValue pgtype.Text
	DisplayValue  pgtype.Text
	Type          pgtype.Text
}

type SysUser struct {
	Uuid            pgtype.UUID
	Name            string
	SecondName      string
	Patronymic      pgtype.Text
	GradebookNumber string
	BirthDate       pgtype.Date
	Email           pgtype.Text
	PhoneNumber     pgtype.Text
	StatusUuid      pgtype.UUID
	Password        pgtype.Text
}

type UserRole struct {
	UserUuid pgtype.UUID
	RoleUuid pgtype.UUID
}
