// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: permission.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGroup = `-- name: CreateGroup :one
insert into auth_group (name)
values ($1)
returning uuid
`

func (q *Queries) CreateGroup(ctx context.Context, name string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createGroup, name)
	var uuid pgtype.UUID
	err := row.Scan(&uuid)
	return uuid, err
}

const createRole = `-- name: CreateRole :one
insert into auth_role (name)
values ($1)
returning uuid
`

func (q *Queries) CreateRole(ctx context.Context, name string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createRole, name)
	var uuid pgtype.UUID
	err := row.Scan(&uuid)
	return uuid, err
}

const deleteGroup = `-- name: DeleteGroup :exec
delete
from auth_group
where uuid = $1
`

func (q *Queries) DeleteGroup(ctx context.Context, uuid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGroup, uuid)
	return err
}

const deleteMembersFromDeletedRole = `-- name: DeleteMembersFromDeletedRole :exec
delete
from user_role
where role_uuid = $1
`

func (q *Queries) DeleteMembersFromDeletedRole(ctx context.Context, roleUuid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMembersFromDeletedRole, roleUuid)
	return err
}

const deleteResourcesFromDeletedGroup = `-- name: DeleteResourcesFromDeletedGroup :exec
delete
from group_resource
where group_uuid = $1
`

func (q *Queries) DeleteResourcesFromDeletedGroup(ctx context.Context, groupUuid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteResourcesFromDeletedGroup, groupUuid)
	return err
}

const deleteRole = `-- name: DeleteRole :exec
delete
from auth_role
where uuid = $1
`

func (q *Queries) DeleteRole(ctx context.Context, uuid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRole, uuid)
	return err
}

const deleteRolesFromDeletedGroup = `-- name: DeleteRolesFromDeletedGroup :exec
delete
from role_group
where group_uuid = $1
`

func (q *Queries) DeleteRolesFromDeletedGroup(ctx context.Context, groupUuid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRolesFromDeletedGroup, groupUuid)
	return err
}

const getGroupByUUID = `-- name: GetGroupByUUID :one
select uuid, name
from auth_group
where uuid = $1
`

func (q *Queries) GetGroupByUUID(ctx context.Context, uuid pgtype.UUID) (AuthGroup, error) {
	row := q.db.QueryRow(ctx, getGroupByUUID, uuid)
	var i AuthGroup
	err := row.Scan(&i.Uuid, &i.Name)
	return i, err
}

const getGroupList = `-- name: GetGroupList :many
select uuid, name
from auth_group
`

func (q *Queries) GetGroupList(ctx context.Context) ([]AuthGroup, error) {
	rows, err := q.db.Query(ctx, getGroupList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthGroup
	for rows.Next() {
		var i AuthGroup
		if err := rows.Scan(&i.Uuid, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupListWithPagination = `-- name: GetGroupListWithPagination :many
select uuid, name, count(*) over() total_records
from auth_group
limit $1 offset $2
`

type GetGroupListWithPaginationParams struct {
	Limit  int32
	Offset int32
}

type GetGroupListWithPaginationRow struct {
	Uuid         pgtype.UUID
	Name         string
	TotalRecords int64
}

func (q *Queries) GetGroupListWithPagination(ctx context.Context, arg GetGroupListWithPaginationParams) ([]GetGroupListWithPaginationRow, error) {
	rows, err := q.db.Query(ctx, getGroupListWithPagination, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGroupListWithPaginationRow
	for rows.Next() {
		var i GetGroupListWithPaginationRow
		if err := rows.Scan(&i.Uuid, &i.Name, &i.TotalRecords); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupResources = `-- name: GetGroupResources :many
select r.uuid, r.value
from group_resource g
         join resource r on g.resource_uuid = r.uuid
where g.group_uuid = $1
`

func (q *Queries) GetGroupResources(ctx context.Context, groupUuid pgtype.UUID) ([]Resource, error) {
	rows, err := q.db.Query(ctx, getGroupResources, groupUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Resource
	for rows.Next() {
		var i Resource
		if err := rows.Scan(&i.Uuid, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupRoles = `-- name: GetGroupRoles :many
select r.uuid, r.name
from auth_role r
         join role_group g on r.uuid = g.role_uuid
where g.group_uuid = $1
`

func (q *Queries) GetGroupRoles(ctx context.Context, groupUuid pgtype.UUID) ([]AuthRole, error) {
	rows, err := q.db.Query(ctx, getGroupRoles, groupUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthRole
	for rows.Next() {
		var i AuthRole
		if err := rows.Scan(&i.Uuid, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoleByUUID = `-- name: GetRoleByUUID :one
select uuid, name
from auth_role
where uuid = $1
`

func (q *Queries) GetRoleByUUID(ctx context.Context, uuid pgtype.UUID) (AuthRole, error) {
	row := q.db.QueryRow(ctx, getRoleByUUID, uuid)
	var i AuthRole
	err := row.Scan(&i.Uuid, &i.Name)
	return i, err
}

const getRoleList = `-- name: GetRoleList :many
select uuid, name
from auth_role
`

func (q *Queries) GetRoleList(ctx context.Context) ([]AuthRole, error) {
	rows, err := q.db.Query(ctx, getRoleList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthRole
	for rows.Next() {
		var i AuthRole
		if err := rows.Scan(&i.Uuid, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoleListWithPagination = `-- name: GetRoleListWithPagination :many
select uuid, name, count(*) over() total_records
from auth_role
limit $1 offset $2
`

type GetRoleListWithPaginationParams struct {
	Limit  int32
	Offset int32
}

type GetRoleListWithPaginationRow struct {
	Uuid         pgtype.UUID
	Name         string
	TotalRecords int64
}

func (q *Queries) GetRoleListWithPagination(ctx context.Context, arg GetRoleListWithPaginationParams) ([]GetRoleListWithPaginationRow, error) {
	rows, err := q.db.Query(ctx, getRoleListWithPagination, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRoleListWithPaginationRow
	for rows.Next() {
		var i GetRoleListWithPaginationRow
		if err := rows.Scan(&i.Uuid, &i.Name, &i.TotalRecords); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoleMembers = `-- name: GetRoleMembers :many
select u.uuid, u.name, u.second_name, u.patronymic, u.gradebook_number, u.birth_date, u.email, u.phone_number, u.status_uuid, u.password, u.salt
from sys_user u
         join user_role r on r.user_uuid = u.uuid
where role_uuid = $1
`

func (q *Queries) GetRoleMembers(ctx context.Context, roleUuid pgtype.UUID) ([]SysUser, error) {
	rows, err := q.db.Query(ctx, getRoleMembers, roleUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SysUser
	for rows.Next() {
		var i SysUser
		if err := rows.Scan(
			&i.Uuid,
			&i.Name,
			&i.SecondName,
			&i.Patronymic,
			&i.GradebookNumber,
			&i.BirthDate,
			&i.Email,
			&i.PhoneNumber,
			&i.StatusUuid,
			&i.Password,
			&i.Salt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeMembersFromRole = `-- name: RemoveMembersFromRole :exec
DELETE
FROM user_role u
    USING UNNEST($1::uuid[]) AS ids(id)
WHERE u.uuid = ids.id
`

func (q *Queries) RemoveMembersFromRole(ctx context.Context, dollar_1 []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, removeMembersFromRole, dollar_1)
	return err
}

const removeResourcesFromGroup = `-- name: RemoveResourcesFromGroup :exec
DELETE
FROM group_resource r
    USING UNNEST($1::uuid[]) AS ids(id)
WHERE r.uuid = ids.id
`

func (q *Queries) RemoveResourcesFromGroup(ctx context.Context, dollar_1 []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, removeResourcesFromGroup, dollar_1)
	return err
}

const removeRolesFromGroup = `-- name: RemoveRolesFromGroup :exec
DELETE
FROM role_group u
    USING UNNEST($1::uuid[]) AS ids(id)
WHERE u.uuid = ids.id
`

func (q *Queries) RemoveRolesFromGroup(ctx context.Context, dollar_1 []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, removeRolesFromGroup, dollar_1)
	return err
}

const updateGroup = `-- name: UpdateGroup :exec
update auth_group
set name = $1
where uuid = $2
`

type UpdateGroupParams struct {
	Name string
	Uuid pgtype.UUID
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) error {
	_, err := q.db.Exec(ctx, updateGroup, arg.Name, arg.Uuid)
	return err
}

const updateRole = `-- name: UpdateRole :exec
update auth_role
set name = $1
where uuid = $2
`

type UpdateRoleParams struct {
	Name string
	Uuid pgtype.UUID
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) error {
	_, err := q.db.Exec(ctx, updateRole, arg.Name, arg.Uuid)
	return err
}
