// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: resource_query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const batchDeleteResources = `-- name: BatchDeleteResources :exec
DELETE FROM resource u
    USING UNNEST($1::uuid[]) AS ids(id)
WHERE u.uuid = ids.id
`

func (q *Queries) BatchDeleteResources(ctx context.Context, dollar_1 []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, batchDeleteResources, dollar_1)
	return err
}

const getResourceList = `-- name: GetResourceList :many
select uuid, value from resource
`

func (q *Queries) GetResourceList(ctx context.Context) ([]Resource, error) {
	rows, err := q.db.Query(ctx, getResourceList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Resource
	for rows.Next() {
		var i Resource
		if err := rows.Scan(&i.Uuid, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
